AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Rewrite jpg and png requests to webp if the browser supports webp
Resources:
  ViewerRequestFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: s3://aws-lambda-edge-image2webp/viewer-request-function.zip
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 5
      Role: !GetAtt WebpExecutionRole.Arn
      FunctionName: imageTransformRequest
  OriginResponseFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: s3://aws-lambda-edge-image2webp/origin-response-function.zip
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 5
      Role: !GetAtt WebpExecutionRole.Arn
      FunctionName: imageTransformResponse

  # ==== ROLES ==== #
  WebpExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com

  # ==== POLICIES ==== #
  PublishLogsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allows functions to write logs
      Roles:
      - !Ref WebpExecutionRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Sid: ExampleStmt1
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
          - Effect: Allow
            Sid: ExampleStmt2
            Action:
            - s3:GetObject
            - s3:PutObject
            - s3-object-lambda:PutObject
            - s3-object-lambda:GetObject
            Resource: 'arn:aws:s3:::aws-lambda-edge-image2webp/*'